### ISSUE TITLE
support(animations): provide additional info on issue #26265

### ISSUE THREAD

**Issue by bampakoa** [angularathens/2nd-workshop-angular-contrib#14]
You can approach the issue https://github.com/angular/angular/issues/26265 in two possible ways:

- Try to investigate the rare case that happens.
- Add a comment to the issue asking the author for more information about the problem.

**Comment by nicholasp** [comment]
shall I take this?

**Comment by bampakoa** [comment]
Thank you @nicholasp for your participation. You can now interact directly with the issue in the Angular repo 🙏 

Related comment: https://github.com/angular/angular/issues/26265#issuecomment-707937969
