### ISSUE TITLE
support(zone.js): add reproduction for issue #31700

### ISSUE THREAD

**Issue by bampakoa** [angularathens/2nd-workshop-angular-contrib#17]
Follow the steps below to provide reproduction steps for issue https://github.com/angular/angular/issues/31700:

1. Create a StackBlitz sample that reproduces the problem mentioned in the issue.
2. Add a proper comment to the issue stating the link of your sample.

You can start working on Angular with StackBlitz [here](https://stackblitz.com/fork/angular-ivy).

**Comment by vlasischar** [comment]
Can I take this?
