### ISSUE TITLE
support(upgrade): add reproduction for issue #37936

### ISSUE THREAD

**Issue by bampakoa** [angularathens/2nd-workshop-angular-contrib#18]
Follow the steps below to provide reproduction steps for issue https://github.com/angular/angular/issues/37936:

1. Create a GitHub repository that reproduces the problem mentioned in the issue.
2. Add a proper comment to the issue stating the link of your repository.

**Comment by gkalpak** [comment]
If possible, it is preferrable to create reproductions in [StackBlitz](https://stackblitz.com/fork/angular-ivy).
<sub>For issues that cannot be reproduced in StackBlitz (e.g. issues involvinf ServiceWorkers, server-side rendering, a specific build configuration, etc.), you can create a GitHub repository with a minimal project that reproduces the issue.</sub>
