### ISSUE TITLE
fix(docs): update output directory name in Deployment guide

### ISSUE THREAD

**Issue by gkalpak** [angularathens/2nd-workshop-angular-contrib#2]
The default output directory in the [Deployment guide][1] ([source code][2]) is outdated. More specifically, the default output directory is no longer `dist/` but `dist/project-name/`.

The following lines need fixing:

- [L100]:
    ```diff
    -2. Copy _everything_ within the output folder (`dist/` by default) to a folder on the server.
    +2. Copy _everything_ within the output folder (`dist/project-name/` by default) to a folder on the server.
    ```

- [L214] and [L218], where I would change `dist/` to just `project-name/`:
    ```diff
    # Line 214
    -  #    |-- dist
    +  #    |-- project-name
    
    # Line 218
    -      folderDir = settings.public_folder + '/dist'  # ng build output folder
    +       folderDir = settings.public_folder + '/project-name'  # ng build output folder
    ```

- [L386]:
    ```diff
    -List the generated bundles in the `dist/` folder.
    +List the generated bundles in the `dist/project-name/` folder.
    ```

- [L390]:
    ```diff
    -  ls dist/*.js
    +  ls dist/project-name/*.js
    ```

- [L399]:
    ```diff
    -  node_modules/.bin/source-map-explorer dist/main*
    +  node_modules/.bin/source-map-explorer dist/project-name/main*
    ```

Related PR:
- angular/angular#38770

<sub>If the above PR has been merged, some of the aforementioned issues may be fixed.</sub>

[1]: https://angular.io/guide/deployment
[2]: https://github.com/angular/angular/blob/master/aio/content/guide/deployment.md
[L100]: https://github.com/angular/angular/blame/4ede190571595c4a74abe2b320f5a4dc3c61a967/aio/content/guide/deployment.md#L100
[L214]: https://github.com/angular/angular/blame/4ede190571595c4a74abe2b320f5a4dc3c61a967/aio/content/guide/deployment.md#L214
[L218]: https://github.com/angular/angular/blame/4ede190571595c4a74abe2b320f5a4dc3c61a967/aio/content/guide/deployment.md#L218
[L386]: https://github.com/angular/angular/blame/4ede190571595c4a74abe2b320f5a4dc3c61a967/aio/content/guide/deployment.md#L386
[L390]: https://github.com/angular/angular/blame/4ede190571595c4a74abe2b320f5a4dc3c61a967/aio/content/guide/deployment.md#L390
[L399]: https://github.com/angular/angular/blame/4ede190571595c4a74abe2b320f5a4dc3c61a967/aio/content/guide/deployment.md#L399

**Comment by bampakoa** [comment]
@gkalpak the second related PR has been merged. Could you please update the description of the issue accordingly?

**Comment by macvag** [comment]
Can I take it?

**Comment by gkalpak** [comment]
For reference, here is the PR: angular/angular#39247

##
👏 @macvag 

Closing this issue, since a PR has been successfully submitted.
