### ISSUE TITLE
docs(core): fix typo in the "Template statements" guide

### ISSUE THREAD

**Issue by bampakoa** [angularathens/2nd-workshop-angular-contrib#20]
In the [line 17](https://github.com/angular/angular/blame/master/aio/content/guide/template-statements.md#L17) of the **Template statements** guide, the word `function` must be changed to `method` because `deleteHero` is a method of the component.

A preview of the guide is available [here](https://angular.io/guide/template-statements#template-statements).

**Comment by CharaLagou** [comment]
Shall I take this up?

**Comment by bampakoa** [comment]
Sure @CharaLagou go on!

**Comment by CharaLagou** [comment]
Super! I've submitted the PR https://github.com/angular/angular/pull/39244

**Comment by gkalpak** [comment]
👏 @CharaLagou 

Closing this issue, since a PR has been successfully submitted.
