### ISSUE TITLE
docs(core): minor fixes in the "View encapsulation" guide

### ISSUE THREAD

**Issue by bampakoa** [angularathens/2nd-workshop-angular-contrib#21]
The following minor changes should be fixed in the [View encapsulation](https://angular.io/guide/view-encapsulation) guide:

1.  In the [line 27](https://github.com/angular/angular/blame/master/aio/content/guide/view-encapsulation.md#L27), the word `components` should be changed to `component's`.

2. In the [line 66](https://github.com/angular/angular/blame/master/aio/content/guide/view-encapsulation.md#L66), the phrase `and you never refer to them` should be changed to `and you should never refer to them` to indicate the importance of not relying on these attributes in the application code. _Consider moving part of this paragraph to a `div` styled with `alert is-helpful` class_.

**Comment by pankyriazo** [comment]
Hello, I would like to try and fix this issue.

**Comment by gkalpak** [comment]
For reference, here is the PR: angular/angular#39246

##
👏 @pkyriazo 

Closing this issue, since a PR has been successfully submitted.
