### ISSUE TITLE
docs(core): fix typo in the "Property binding" guide

### ISSUE THREAD

**Issue by bampakoa** [angularathens/2nd-workshop-angular-contrib#22]
In [line 5](https://github.com/angular/angular/blame/master/aio/content/guide/property-binding.md#L5) of the **Property binding** guide, the word `programatically` is not grammatically correct.

A preview of the guide is available [here](https://angular.io/guide/property-binding).

**Comment by gvrettos** [comment]
May I fix this typo?

**Comment by bampakoa** [comment]
@gvrettos please mention the respective PR of the angular repo here when it is available 🙏

**Comment by gvrettos** [comment]
This is the PR of the angular repo:
angular/angular#39569
