### ISSUE TITLE
docs(core): add an entry to the glossary about microsyntax

### ISSUE THREAD

**Issue by bampakoa** [angularathens/2nd-workshop-angular-contrib#24]
The Structural Directives guide contains a section that explains the meaning of microsyntax in https://angular.io/guide/structural-directives#microsyntax.
Add a new entry in the [Glossary](https://angular.io/guide/glossary) that explains microsyntax briefly.

Related issue: https://github.com/angular/angular/issues/39784

**Comment by tzimpoulog** [comment]
Picking up this issue

**Comment by patelvimal** [comment]
@bampakoa  Can I take this one? We just need to explain microsyntax briefly along with an example. Right?

**Comment by bampakoa** [comment]
@patelvimal thanks very much for your willingness to work on this issue but this repository contains topics that are related to Angular Athens workshops. However, feel free to work on the related issue that exists in the Angular repository 😃 

P.S.: If you need any help on the issue, let me know. I would be happy to assist 😃

**Comment by patelvimal** [comment]
ok, no issues, can you please confirm if my understanding of this issue is correct or not?

**Comment by bampakoa** [comment]
@patelvimal yes, it should be correct. But for sure, you can add a comment in the Angular issue and ask for more information. They will help for sure 😉
