### ISSUE TITLE
docs(core): add an entry to the glossary about template input variable

### ISSUE THREAD

**Issue by bampakoa** [angularathens/2nd-workshop-angular-contrib#25]
The meaning of **template input variable** is used in several guides through the angular.io documentation such as the [Built-in directives](https://angular.io/guide/built-in-directives#template-input-variables) and the [Structural directives](https://angular.io/guide/structural-directives#template-input-variable) guide.
Add a brief overview of the  **template input variable** in the [Glossary](https://angular.io/guide/glossary).

Related issue: https://github.com/angular/angular/issues/39783

**Comment by giannissmirnios** [comment]
Picking up this issue

**Comment by giannissmirnios** [comment]
Created: https://github.com/angular/angular/pull/39861
