### ISSUE TITLE
docs: fix typo in the Inputs-Outputs guide

### ISSUE THREAD

**Issue by bampakoa** [angularathens/2nd-workshop-angular-contrib#28]
- In [line 25](https://github.com/angular/angular/blame/master/aio/content/guide/inputs-outputs.md#L25),  the word `@Output` should be enclosed in backticks.
- In [line 117](https://github.com/angular/angular/blame/master/aio/content/guide/inputs-outputs.md#L117),  there is a missing `In` that should go in front of the sentence ` The following example...` so that its meaning is more clear.

A preview of the guide is available [here](https://angular.io/guide/inputs-outputs).

**Comment by christos-P** [comment]
Could I take it ?

**Comment by christos-P** [comment]
PR has been opened.

**Comment by bampakoa** [comment]
@christos-P can you please mention the PR in your comment?

**Comment by christos-P** [comment]
@bampakoa sure thing, https://github.com/angular/angular/pull/39856.

**Comment by bampakoa** [comment]
Congratulations on your contribution @christos-P 😃

**Comment by christos-P** [comment]
@bampakoa Thank you very much :)
