### ISSUE TITLE
docs: fix typo in the Two-way Binding guide

### ISSUE THREAD

**Issue by bampakoa** [angularathens/2nd-workshop-angular-contrib#29]
In [line 4](https://github.com/angular/angular/blame/master/aio/content/guide/two-way-binding.md#L4), remove the duplicate `binding` word.

A preview of the guide is available [here](https://angular.io/guide/two-way-binding).

**Comment by bluemyria** [comment]
I take it :)

**Comment by bluemyria** [comment]
https://github.com/angular/angular/pull/39859

Thank you for the support @bampakoa :D

**Comment by bampakoa** [comment]
Congratulations @bluemyria 👏 👏
