### ISSUE TITLE
docs(forms): fix typo in the Reactive Forms guide

### ISSUE THREAD

**Issue by profanis** [angularathens/2nd-workshop-angular-contrib#5]
On the page where the usage of formGroup directive is explained, has a minor typo. Instead of `profileForm` it's `profile form` 

This line:
> Note that just as a form group contains a group of controls, the profile form FormGroup is bound to the

should be
> Note that just as a form group contains a group of controls, the profileForm FormGroup is bound to the

_**Notice that the `profileForm` value should be enclosed in backticks to indicate that it is text that appears in code.**_

Related Link: [Grouping Form Controls](https://angular.io/guide/reactive-forms#grouping-form-controls) ([Source Code](https://github.com/angular/angular/blob/master/aio/content/guide/reactive-forms.md))

**Comment by d0rian7** [comment]
I could try to fix that

**Comment by d0rian7** [comment]
https://github.com/angular/angular/pull/39245

**Comment by bampakoa** [comment]
@d0rian7 your PR was merged! Congratulations on your first contribution to Angular 👏 🥳
